// do not edit, automatically generated by genairdataconst.cc

#include "airdata.h"

template<> constexpr typename AirData<float>::float_t AirData<float>::speed_of_sound_std = 661.442;
template<> constexpr typename AirData<double>::float_t AirData<double>::speed_of_sound_std = 661.442;
